# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/Threads.Api.sln
    - name: Build
      run: dotnet build ./src/Threads.Api.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test ./src/Threads.Api.sln --verbosity normal
    - name: Pack
      run: dotnet pack ./src/Threads.Api/Threads.Api.csproj --configuration Release --no-build --output ./artifacts

    - uses: actions/upload-artifact@master
      with:
        name: package
        path: ./artifacts/*.nupkg